### ISSUE TITLE
fork cannot run tests defined in a test suite class

### ISSUE THREAD

**Issue by asos-paulmacdonald** [shazam/fork#112]
Hi, I'm trying to run a particular set of tests defined in a test suite:
`package com.asos.instrumentation.acceptance.testsuites;

import com.asos.instrumentation.acceptance.product.ProductDetailsPageTest;
import com.asos.instrumentation.acceptance.product.ProductFlagTest;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({ProductDetailsPageTest.class, ProductFlagTest.class})

public class PDPTestSuite {
}`

I've pointed fork at the test suite package:
`forkTestPackage=com.asos.instrumentation.acceptance.testsuites`

but it seems that fork does not like this:
`Error when trying to find test classes
com.shazam.fork.suite.NoTestCasesFoundException: No tests cases were found in the test APK: /Users/...
        at com.shazam.fork.suite.TestSuiteLoader.loadTestSuite(TestSuiteLoader.java:52)
...
`

Any ideas? Is this something that can be supported in a future update?
Cheers,
Paul MacDonald.

p.s. I can confirm that the tests run successfully when triggered manually in Android studio 😄

**Comment by iordanis** [comment]
Because of some pre-processing we do to test APKs, the test suites are unsupported and therefore tests are not being picked up.

**Comment by asos-paulmacdonald** [comment]
Is this something that can be supported in a future update?

**Comment by iordanis** [comment]
I don't think we'll prioritise this over other features, but wouldn't be against a PR.

Organising tests in packages wouldn't be the same, but could be functionally good enough for your purposes in the meantime (unless you group them depending on the context).

**Comment by iordanis** [comment]
I think we could support a similar thing via annotation filters, so closing this.
