### ISSUE TITLE
Generated gif screenshots are out of order

### ISSUE THREAD

**Issue by sean-kenny** [shazam/fork#118]
I believe that since there is no ordering of the file names after they are listed from the system, there is a possibility for the generated gif to be random/out of order.

I've hit this a few times now with generated gifs on ci machines..

I think the fix is to simply have a method in `FileManager` that returns an ordered list of files based on the number at the end of the file.

**Comment by iordanis** [comment]
I think since most of our devices are > API 19, we're going to remove the screenshot/gif functionality and invest more on the videos solution. Sorry! :)
