### ISSUE TITLE
Allow arbitrary metadata to be reported in JUnit XML

### ISSUE THREAD

**Issue by iordanis** [shazam/fork#123]
According to the JUnit XML ([long discussion here](http://help.catchsoftware.com/display/ET/JUnit+Format)), we can store arbitrary metadata in the properties of a "testsuite". Since we treat each test method as an individual test, that is good enough for each test method.

We will do that with an annotation that will be included in a client JAR. We'll avoid complications of repeating annotations so the format can be: `@TestMetadata("key1", "value1", "key2", "value2")`.

**Comment by veniosg** [comment]
FYI the current plan is that, on the report level, this would be added on the testSuite level rather than the tests themselves. In fork this is not an issue as every testSuite only contains a single test.
