### ISSUE TITLE
Run gradle plugin with release version?

### ISSUE THREAD

**Issue by Rackles** [shazam/fork#132]
Hi,

is it possible to run the gradle plugin with a release apk/custom defined apk. 

As of right now I just found the arguments of the standalone to define the apks. 

Thanks for any help.

**Comment by iordanis** [comment]
Closing this as an old one. The supported methods of execution are standalone (via runner) or via a plugin that then refers to your application & instrumentation APKs.

You could run the release flavour of the fork tests if you so prefer.
