### ISSUE TITLE
Path to external storage directory is hardcoded

### ISSUE THREAD

**Issue by TarCV** [shazam/fork#146]
https://github.com/shazam/fork/blob/4a05c2a8d4bc267e9b4b4a4f8bdc27ba05a78c22/fork-runner/src/main/java/com/shazam/fork/system/io/RemoteFileManager.java#L29

According to Android linter the path to external storage mount directory should not be hardcoded.
For example `IDevice#getMountPoint(MNT_EXTERNAL_STORAGE)` can be used instead.
I have actually encountered devices where `adb shell echo $EXTERNAL_STORAGE` returns a path different from `/sdcard`.

I think it's possible that this issue causes videos not being recorded like in #138

**Comment by AndreiZaitcev** [comment]
This should be resolved by ee92adf066455bd8f3b173d7e5dcb9c1da90bb3d
