### ISSUE TITLE
Fork marks build as failed, even when all tests have passed.

### ISSUE THREAD

**Issue by yogurtearl** [shazam/fork#30]
Fork often fails the build even when all the tests pass.

This is using 0.10.0. ( we can't use 0.11.0, because the screenshot stuff is causing problems and it can't be disabled. )

This happens frequently with 20+ devices attached.

```
Pools remaining: 0
  0 E    0 F   123 P: older=api0-17
  0 E    0 F   123 P: Newer=api18-up
No suppressed tests.
Device  pending after 120 seconds of inactivity
Apparently, no devices pending. Aborting in 15sec
```

Related to this code: 
https://github.com/shazam/fork/blob/d0e1dce11d2214c7c1e91fca6c928b9df44723e5/src/main/java/com/shazam/fork/runtime/TimeoutAlert.java

**Comment by iordanis** [comment]
This would be tricky to debug without knowing what the tests/setup. Looks like a bug in our watchdog logic. I wanted to improve it because it's probably the least stable part of Fork.

**Comment by iordanis** [comment]
The current incarnation of the swimlane has been removed from master, as it was tied to the watchdog that was killing legitimate test runs. Will be fixing in #35.
