### ISSUE TITLE
com/github/mustachejava/MustacheFactory : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by tmelz** [shazam/fork#40]
Recently I started getting this error:
```
* What went wrong:
Execution failed for task ':app:forkDebug'.
> com/github/mustachejava/MustacheFactory : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Does fork now require Java 8?

**Comment by iordanis** [comment]
Definitely not, check https://github.com/shazam/fork/blob/master/build.gradle : source & target compatibility is set to Java 7. Not sure why you're getting this.

**Comment by tmelz** [comment]
Looking at https://github.com/spullara/mustache.java/issues/124, it looks like v0.9+ is Java 8 targeted, and 0.8 is the last Java 7 targeted release.

**Comment by iordanis** [comment]
Ah damn, it must be just the mustache library, which I updated recently. Check line 92 from https://github.com/spullara/mustache.java/blob/6b32476456ad049d7237e6435ce3375215f1a68e/pom.xml

**Comment by tmelz** [comment]
Cool. Are there any blockers to reverting back to 0.8? Also, I'm currently just pointing to 
```
classpath 'com.shazam.fork:fork-gradle-plugin:1.0.0-RC1-SNAPSHOT'
```
which unfortunately doesn't lead to reproducible builds. Any chance you guys could go back and push a minor version update?

**Comment by iordanis** [comment]
Well that's the downside of using snapshots, right? :) I think we can revert to 0.8 for Mustache, since it's the only one targetting Java 8. Feel free to send a PR and I'll merge pretty soon.

**Comment by tmelz** [comment]
See #41

**Comment by ericjee** [comment]
com/shazam/fork/reporter/gradle/JenkinsPlugin : Unsupported major.minor version 52.0
got another error, any ideas?

**Comment by iordanis** [comment]
Can you check if the next mustache version is brought in transitively? If 0.8 is the one that's used you shouldn't be getting this. Later versions require Java 8 which seems to be your case.

I think it's also time to upgrade that dependency (and require Java 8).
