### ISSUE TITLE
Maven central update requested

### ISSUE THREAD

**Issue by tmelz** [shazam/fork#42]
Having snapshots is really nice, but to use fork for CI we need to be locked down on a stable version. Would you guys mind publishing the current state as a minor version?

**Comment by iordanis** [comment]
My only concern for a final 1.0.0 is #15. Has it been working well for you?

**Comment by tmelz** [comment]
Haven't spent much time on it so hard to say, honestly i was thinking just like 0.2 (last version was 0.12, right?).

**Comment by iordanis** [comment]
Fair enough. Can always make that a patch release.

**Comment by yogurtearl** [comment]
disabling the built screenshots would be really nice to have in the next release. :)

**Comment by iordanis** [comment]
Good to have your input, Michael :) Are the screenshots working at all for you? I found for slow tests they generate huge files, thus reports. I'm leaving towards just having videos or nothing pre kit kat, for failed tests.

**Comment by iordanis** [comment]
Released 1.0.0-RC1
