### ISSUE TITLE
Allow changing the order of tests that are run

### ISSUE THREAD

**Issue by brennantaylor** [shazam/fork#59]
It appears as if fork runs tests alphabetically based on package+class name.

My thinking is similar to how TeamCity will run failing tests from the last build as the first tests of the current build to speedup feedback.

Perhaps tests that match a provided regular expression (eg `failingTest1,failingTest2`) will be prioritized before the other tests. Coupled with the "fail fast" feature requested elsewhere this could help decrease the load on environments with shared device resources.

**Comment by iordanis** [comment]
Closing this, as it is an old issue and has received no traction.
