### ISSUE TITLE
Simplify package configuration: test package should be the same as app package

### ISSUE THREAD

**Issue by iordanis** [shazam/fork#63]
By default Android Studio creates tests in the same package as the package of the main application, e.g. `com.example`. 

Even if the eventual package of the test application has the `test` suffix (`com.example.test`), the test classes are still in `com.example`.

Fork should be modified to follow the default AS behaviour.

**Comment by pavanagarwal** [comment]
Hi. Has this been addressed in 1.3.0 ?

**Comment by iordanis** [comment]
Not yet. I recommend you configure the test package manually till then.

**Comment by iordanis** [comment]
We will additionally simplify the configuration around test packages.
