### ISSUE TITLE
When using fork-gradle-plugin guava version 18 causes android lint to crash

### ISSUE THREAD

**Issue by brennantaylor** [shazam/fork#65]
Guava 17.0 works just fine.

**Comment by iordanis** [comment]
What sort of issues do you get? I'm not sure how that's related to the fork plugin.

**Comment by brennantaylor** [comment]
lint crashes because classes it expects are no longer found.

**Comment by brennantaylor** [comment]
Does this require more explanation?

**Comment by iordanis** [comment]
Yes please. Based just on your description it could be gradle picking v18 and lint depending on v17 classes that are not in 18. Any help/stacktrace/sample project could shed some light.
