### ISSUE TITLE
Device pool fails to run all the tests

### ISSUE THREAD

**Issue by yogurtearl** [shazam/fork#7]
I had this problem (INSTALL_FAILED_UID_CHANGED):
https://code.google.com/p/android/issues/detail?id=79716

Which caused the app to not be installed.

So Fork gave this error:
"Test run failed: Unable to find instrumentation target package:"

Because of the above error forked failed to run most of the tests in that pool, but still reported SUCCESS as the build status. 

Fork should fail the overall build status in this case and really any time there is an issue that prevents a test case from being run, the build should fail. ( this could be an optional setting that is configurable )

**Comment by iordanis** [comment]
Closing as we haven't been able to reproduce. Will reraise if anyone runs into it again.
