### ISSUE TITLE
Enable code coverage.

### ISSUE THREAD

**Issue by traviswestbrook** [shazam/fork#71]
As far as I can tell Fork does not support code coverage. I think there should be an optional configuration for enabling code coverage and specifying the directory to which the coverage files should be output to. I can submit a pull request to do so, just wanted to be sure I wasn't missing something or if there was a reason for not supporting the generation of the coverage files.

**Comment by traviswestbrook** [comment]
Submitted a pull request #77. Decided to output the coverage files to the fork directory.

**Comment by iordanis** [comment]
This is now supported by setting the flag `isCoverageEnabled` to `true` in the DSL.
