### ISSUE TITLE
Test cases are ignored when method name contains characters like Chinese

### ISSUE THREAD

**Issue by ericjee** [shazam/fork#78]
Hi, since upgrade fork to the new release 1.3.0, My test cases are ignored to execute, i've notice that only the method name in Chinese is not executed, any ideas about this? 
I'm using 2.10 and AS plugin 2.1.0-beta1, any suggestions will be appreciated:)

I feel it is because of these file changes, Do we changed a way to get the test method ?
- TestCaseEvent.java
- TestRun.java
- TestRunFactory.java
- TestRunParameters.java

**Comment by fpezzato** [comment]
Hi @ericjee, thanks for your feedback!

>Do we changed a way to get the test method?

Yes,  the way the tests methods are loaded has been slightly changed.
Could you please provide an example of a test class and method not executed?

Thanks!

ps.
I guess a good point to start our investigation might be in the classes:
* https://github.com/shazam/fork/blob/master/fork-runner/src/main/java/com/shazam/fork/runner/TestRun.java#L59
* https://github.com/shazam/fork/blob/master/fork-runner/src/main/java/com/shazam/fork/suite/TestClassLoader.java#L44

**Comment by ericjee** [comment]
@fpezzato thx for your help, Following is an example:)

@Test public void test添加新客户(), this one is ignored
@Test public void addNewCustomer(),  this one is executed

i saw your comments, maybe i can create a UT case to check what will be return from from(testClasses).transformAndConcat(...).toList();

**Comment by fpezzato** [comment]
@ericjee  
I had a quick look.
Looks like on our side everything is fine, the bug seems to be in the class  com.android.ddmlib.testrunner.RemoteAndroidTestRunner#executeShellCommand (it's google code).

In fact: via shell 
```
adb shell am instrument -w -r  -e class demotest.com.MySingleClassTest#test添加新客户t  demotest.com/android.support.test.runner.AndroidJUnitRunner
```
works. 

But via 
```
 mRemoteDevice.executeShellCommand(runCaseCommandStr ....)```  
the test is not executed.

**Comment by iordanis** [comment]
This is an issue with ddmlib, so nothing we can fix on our side.
