### ISSUE TITLE
JUnit3 tests ignored in Fork 1.3.0 (not 1.2.0)

### ISSUE THREAD

**Issue by tmelz** [shazam/fork#86]
In Fork 1.3.0, JUnit3 tests (those extending TestCase instead of using `@Test`) are silently ignored. For example:

``` java
public class ExampleJunit3Test extends InstrumentationTestCase {
    public void testExample() {
        assertEquals(true, true);
    }
}
```

This test will run in Fork 1.2.0 but on 1.3.0 it isn't present in the output.

**Comment by iordanis** [comment]
This will still work i think if you add the JUnit 4 runner (@RunWith(AndroidJunitRunner.class) and annotate the test with @Test and no other changes. Out of curiosity, any reasons you use JUnit 3 syntax?

**Comment by tmelz** [comment]
We have a lot of older tests written before Android had JUnit4 support. Yep, you're right that the tests will work with those changes. I'm not completely against migrating them but it'd be quite a bit of tedious work (though likely script-able). Do you have an idea why this broke?

**Comment by iordanis** [comment]
It had to do with how we look for tests. In the past we only cared about test classes, obviously to improve the execution, we're now doing individual methods. So we only introduced scanning for JUnit 4 type tests (looking for the annotation) rather than JUnit3 (test-naming based).

**Comment by tmelz** [comment]
Would you be open to a PR for JUnit3 support (behind a configuration flag if desired)? At first glance the change looks straightforward, modifying `TestClassFactory#testMethodsPredicate` to to return `true` if `containsTestAnnotation` or if the test name starts with `"test"`(followed by a non-lower-case character).
https://github.com/shazam/fork/blob/a3f8d8fbc80e38be3423a4229311ca70c338ef23/fork-runner/src/main/java/com/shazam/fork/suite/TestClassFactory.java#L71

It'd be more thorough to also check if the class extends `TestCase`, but I think that'd be extra work for minimal gain.

**Comment by iordanis** [comment]
Sure, that would be fine. 

We perhaps need to add that in the documentation, mostly to explain that a mix-and-match of `@Test` and `test*()` will not work in the same test classes. Bear in mind that we will be merging this branch to master soon: https://github.com/shazam/fork/tree/performance. The equivalent code of what you suggested would be somewhere around: https://github.com/shazam/fork/blob/performance/fork-common%2Fsrc%2Fmain%2Fjava%2Fcom%2Fshazam%2Ffork%2Fsuite%2FTestSuiteLoader.java#L64

**Comment by iordanis** [comment]
Few people care for JUnit3 anymore. Closing.
