### ISSUE TITLE
Gradle plugin configuration don't seem to work

### ISSUE THREAD

**Issue by Robertoq7** [shazam/fork#89]
Hi!

I followed the instruction from readme, but I got build error

 

    buildscript {
        repositories {
            mavenCentral()
        }
        dependencies {
            classpath 'com.shazam.fork:fork-gradle-plugin:2.0.0-SNAPSHOT'
        }
    }

    apply plugin: 'com.android.application'
    apply plugin: 'com.shazam.fork'

    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.3"
    ....

>Error:Could not find com.shazam.fork:fork-gradle-plugin:2.0.0-SNAPSHOT.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/fork-gradle-plugin-2.0.0-SNAPSHOT.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/fork-gradle-plugin-2.0.0-SNAPSHOT.jar
    https://repo1.maven.org/maven2/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml
    https://repo1.maven.org/maven2/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/fork-gradle-plugin-2.0.0-SNAPSHOT.pom
    https://repo1.maven.org/maven2/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/fork-gradle-plugin-2.0.0-SNAPSHOT.jar
Required by:
    Grad:app:unspecified

--------------------------------------------------------

Similar, but another problem if the app includes the fabric too:

    buildscript {
        repositories {
            mavenCentral()
            maven { url 'https://maven.fabric.io/public' }
        }

       dependencies {
            classpath 'io.fabric.tools:gradle:1.+'
            classpath 'com.shazam.fork:fork-gradle-plugin:2.0.0-SNAPSHOT'
        }
    }
    apply plugin: 'com.android.application'

    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    apply plugin: 'io.fabric'
    apply plugin: 'com.shazam.fork'

> Error:Could not find com.shazam.fork:fork-gradle-plugin:2.0.0-SNAPSHOT.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/fork-gradle-plugin-2.0.0-SNAPSHOT.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/fork-gradle-plugin-2.0.0-SNAPSHOT.jar
    https://maven.fabric.io/public/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml
    https://maven.fabric.io/public/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/fork-gradle-plugin-2.0.0-SNAPSHOT.pom
    https://maven.fabric.io/public/com/shazam/fork/fork-gradle-plugin/2.0.0-SNAPSHOT/fork-gradle-plugin-2.0.0-SNAPSHOT.jar
Required by:
    MobileTv:mobiletv_tablet:unspecified

Gradle version:

> ------------------------------------------------------------
Gradle 2.10
------------------------------------------------------------

Build time:   2015-12-21 21:15:04 UTC
Build number: none
Revision:     276bdcded730f53aa8c11b479986aafa58e124a6

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)

**Comment by iordanis** [comment]
Hi and sorry for the late reply.

The Fork `2.0.0-SNAPSHOT` cannot be found in the Maven Central release repository which makes sense, since it's still a snapshot. Whenever you use any snapshots you need to tell Gradle to also look in snapshot repos.

Having said that, I'm going to be releasing 2.0.0 today, which means it will be on Maven Central. So this will work as long as you remove the `-SNAPSHOT` from the version.
