### ISSUE TITLE
standalone - fork is unable to find tests

### ISSUE THREAD

**Issue by piccione99** [shazam/fork#91]
Hi There, 

We want to use fork specifically for it's failed test retry feature.  However, fork is unable to find any test cases in the test apk.  When we run spoon against the same exact apk artifacts, it is able to run the tests..  Is there something additional we need to do to get fork to recognize the test cases?  I tried the standalone fork-runner to get the gradle plugin out of the picture entirely, but I'm not sure if I'm setting up the configuration correctly.  

Below is my fork command.  Note that it was unclear from the documentation what these values should be... for --apk I tried both the release apk and the directory of the app... I got further specifying the directory of the app for that argument.    

gradlew fork-runner:run -Pargs='--apk ../HomeHub-UI --test-apk ../HomeHub-UI/App/build/outputs/apk/xfinityhome-mockTest-debug-androidTest-unaligned.apk --config config.json' --debug -Dfork.test.size=medium

Note that in the tests, we are using annotation: "MediumTest"  

Here is config.json:

{
 "fork": {
    "title" : "Fork Report",
    "testPackage" : "com.comcast.xfinityhome.activity.emulatorregression"
  }
}

Here is the relevant error message:

17:49:53.880 [QUIET] [system.out] ERROR ForkRunner:81 - Error when trying to find test classes
17:49:53.880 [QUIET] [system.out] com.shazam.fork.suite.NoTestCasesFoundException: No tests cases were found in the test APK: /Users/yyy/comcast/fork/../HomeHub-UI/App/build/outputs/apk/xfinityhome-mockTest-debug-androidTest-unaligned.apk
17:49:53.880 [QUIET] [system.out] 	at com.shazam.fork.suite.TestSuiteLoader.loadTestSuite(TestSuiteLoader.java:52)
17:49:53.881 [QUIET] [system.out] 	at com.shazam.fork.ForkRunner.run(ForkRunner.java:62)
17:49:53.881 [QUIET] [system.out] 	at com.shazam.fork.Fork.run(Fork.java:45)
17:49:53.881 [QUIET] [system.out] 	at com.shazam.fork.ForkCli.main(ForkCli.java:105)

Thanks for any ideas!

**Comment by fpezzato** [comment]
Hi!

> for --apk I tried both the release apk and the directory of the app.

The expected param is the path to the .apk file of the app. For  example `--apk /path/to/production.APK`. Check this example : https://github.com/shazam/fork#automatic-pooling-1


Also, to avoid  any concatenation problems, have you tried to specify the full path for all the files?
Something like:
`gradlew fork-runner:run -Pargs='
--apk /Users/yyy/comcast/fork/HomeHub-UI/App/build/outputs/apk/xfinityhome-mockTest-debug-unaligned.apk 
--test-apk /Users/yyy/comcast/fork/HomeHub-UI/App/build/outputs/apk/xfinityhome-mockTest-debug-androidTest-unaligned.apk 
--config /Users/yyy/comcast/fork/config.json' --debug -Dfork.test.size=medium`

_(Please check the paths,  in my example I just assumed them based on the debug log)._


If still you have the problem please provide me a demo app with the source code, I could try to run the tests as well!
