### ISSUE TITLE
Gradle DSL method not found

### ISSUE THREAD

**Issue by ericjee** [shazam/fork#92]
Hey guys, is there any DSL configuration changed with v2.1.0-SNAPSHOT ? My gradle start to report "gradle DSL method not found: 'testPackage()' " since i upgraded fork to new version. It was working before with v1.4.0-SNAPSHOT

**Comment by geoffpowell-vividseats** [comment]
I am seeing the same issue with 2.0. Any fixes?

**Comment by iordanis** [comment]
Hi, is this still an issue? If it is can you check the documentation?
