### ISSUE TITLE
Could not find org.smali:dexlib:1.4.2

### ISSUE THREAD

**Issue by dmarin** [shazam/fork#93]
Hi guys!

I am trying to use fork, but I am getting the following error on both versions, the final 2.0.0 and the 2.1.0 SNAPSHOT.

`Error:Could not find org.smali:dexlib:1.4.2.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/org/smali/dexlib/1.4.2/dexlib-1.4.2.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/org/smali/dexlib/1.4.2/dexlib-1.4.2.jar
    https://repo1.maven.org/maven2/org/smali/dexlib/1.4.2/dexlib-1.4.2.pom
    https://repo1.maven.org/maven2/org/smali/dexlib/1.4.2/dexlib-1.4.2.jar
    https://oss.sonatype.org/content/repositories/snapshots/org/smali/dexlib/1.4.2/dexlib-1.4.2.pom
    https://oss.sonatype.org/content/repositories/snapshots/org/smali/dexlib/1.4.2/dexlib-1.4.2.jar
Required by:
    whAndroid:app:unspecified > com.shazam.fork:fork-gradle-plugin:2.1.0-SNAPSHOT > com.shazam.fork:fork:2.1.0-SNAPSHOT > com.shazam.fork:fork-common:2.1.0-SNAPSHOT
`

BTW how are you guys :) all good?

**Comment by dmarin** [comment]
Ok, I found a repo with the missing dependency, so my problem can be fixed by adding the following repository
`maven { url 'https://dl.bintray.com/gost/smali'}`
Ie 
```
buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://dl.bintray.com/gost/smali'}
    }
    dependencies {
        classpath 'com.shazam.fork:fork-gradle-plugin:2.0.0'
    }
}

**Comment by iordanis** [comment]
Hi dude! Make sure you add jcenter as a buildscript dependency:
``` buildscript {
        repositories {
            jcenter()
        }
} ```

**Comment by iordanis** [comment]
Happy to hear you're still on android stuff :)

**Comment by dmarin** [comment]
oooh man! for some reason i thought defining the jcenter repository in the top level build.gradle was good enough

Sorry to waste your time :)

Yeah! Still doing Android and i think i will stick to Android development for a long time :)
