### ISSUE TITLE
"Cannot add task ':app:forkDebugAndroidTest' as a task with that name already exists." 

### ISSUE THREAD

**Issue by arpita184** [shazam/fork#98]
Hi,

I am trying to setup fork for my app and I added

added following two files

- classpath 'com.shazam.fork:fork-gradle-plugin:2.0.0' --> arpita/build.gradle
- apply plugin: 'com.shazam.fork' --> arpita/app/build.gradle

Once I try to sync Gradle project I get Error:
**Cannot add task ':app:forkDebugAndroidTest' as a task with that name already exists.**

I ran gradlew task and I ensured there is no such "forkDebugAndroidTest" task. 

Please let me know if I need to perform any extra steps.

Thanks

**Comment by iordanis** [comment]
Hi (and sorry for the slow reply)

Do you use APK splits?
